canonifyURLs = true
languageCode = 'en-us'
title = 'YWallet Beta docs'

theme = "hugo-theme-relearn"

[params]
themeVariant = "blue"
showVisitedLinks = true
disableLandingPageButton = true
mathJaxInitialize = "{ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']], displayMath: [['$$','$$']], processEscapes: true, processEnvironments: true, skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'], TeX: { equationNumbers: { autoNumber: \"AMS\" } }}}"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[markup]
[markup.highlight]
# if `guessSyntax = true`, there will be no unstyled code even if no language
# was given BUT Mermaid and Math codefences will not work anymore! So this is a
# mandatory setting for your site if you want to use Math codefences
guessSyntax = false
