canonifyURLs = true
languageCode = 'en-us'
title = 'YWallet Beta docs'

theme = "hugo-theme-relearn"

[params]
themeVariant = "blue"
disableLandingPageButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

